id: 72a32ae6-9fbf-424c-872a-cf3dce4f7238
inputs: []
name: Linux Network Troubleshooting v2
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d0c520aa-3202-445f-8a29-00a5886bdcd8
      iscommand: false
      name: ""
      version: -1
    taskid: d0c520aa-3202-445f-8a29-00a5886bdcd8
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerror: true
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      address:
        simple: 34.214.113.182
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Pings an IP or url address, to verify it's up
      id: 0a36a708-3b17-4703-8f29-55dc0413a375
      iscommand: false
      name: Check if hosts responds to Ping
      script: Ping
      type: regular
      version: -1
    taskid: 0a36a708-3b17-4703-8f29-55dc0413a375
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Ping.ret_code
          operator: isExists
      label: "yes"
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 00edfdd5-8e09-4e71-8da5-b0fdeb7e4579
      iscommand: false
      name: Is hosts online?
      type: condition
      version: -1
    taskid: 00edfdd5-8e09-4e71-8da5-b0fdeb7e4579
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 400
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      cmds:
        simple: ip addr show
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Execute commands using Netmiko
      id: fa441465-1c37-4fd8-891b-95209844b767
      iscommand: true
      name: Pull IP Network Configuration
      script: '|||netmiko-cmds'
      tags:
      - report
      type: regular
      version: -1
    taskid: fa441465-1c37-4fd8-891b-95209844b767
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 710,
          "y": 610
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ec8910f6-bb39-430c-873e-0d72b6e094d8
      iscommand: false
      name: Manual Review Status of Host
      type: regular
      version: -1
    taskid: ec8910f6-bb39-430c-873e-0d72b6e094d8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 200,
          "y": 610
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: d1e69ba4-6ef7-42f5-8692-7358e386df2b
      iscommand: true
      name: Close Investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: d1e69ba4-6ef7-42f5-8692-7358e386df2b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 320,
          "y": 1920
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    scriptarguments:
      cmds:
        simple: ss -pnlt
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Execute commands using Netmiko
      id: fdf2007a-c117-4a8c-8b87-c80c6fdbdab8
      iscommand: true
      name: Retrieve List of Active Ports
      script: '|||netmiko-cmds'
      tags:
      - report
      type: regular
      version: -1
    taskid: fdf2007a-c117-4a8c-8b87-c80c6fdbdab8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 710,
          "y": 970
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    scriptarguments:
      data:
        complex:
          accessor: Output
          root: Netmiko
          transformers:
          - args:
              separator:
                value:
                  simple: |2+


            operator: join
      filename:
        simple: network_troubleshooting_report.txt
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Will create a file (using the given data input or entry ID) and upload it to current investigation war room.
      id: bcd05ef0-0d2e-493d-80ab-b9192b59ed8d
      iscommand: false
      name: Create Report
      script: FileCreateAndUpload
      type: regular
      version: -1
    taskid: bcd05ef0-0d2e-493d-80ab-b9192b59ed8d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 710,
          "y": 1140
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      cmds:
        simple: cat /etc/sysconfig/network-scripts/ifcfg-eth0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Execute commands using Netmiko
      id: 3191d751-b257-4f12-8660-e471f35678ce
      iscommand: true
      name: View Network Interface Configuration
      script: '|||netmiko-cmds'
      tags:
      - report
      type: regular
      version: -1
    taskid: 3191d751-b257-4f12-8660-e471f35678ce
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 710,
          "y": 790
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      "NO":
      - "5"
      "yes":
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8fe522b7-8b55-4ca7-8f06-24f5852e6232
      iscommand: false
      name: Should this incident be escalated?
      type: condition
      version: -1
    taskid: 8fe522b7-8b55-4ca7-8f06-24f5852e6232
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 710,
          "y": 1310
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      severity:
        simple: "4"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: ca8a9225-b6a7-4bac-8c17-2f8247565570
      iscommand: true
      name: Increase Incident Severity and Assign to Tier 3 Analyst
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: ca8a9225-b6a7-4bac-8c17-2f8247565570
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 980,
          "y": 1510
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 318fe6d7-5bfa-4697-8979-520f17724110
      iscommand: false
      name: Tier 3 Review
      type: regular
      version: -1
    taskid: 318fe6d7-5bfa-4697-8979-520f17724110
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 980,
          "y": 1690
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1965,
        "width": 1160,
        "x": 200,
        "y": 50
      }
    }
  }
